{% set version = "0.3.1" %}

package:
  name: panel
  version: {{ version }}

source:
  url: https://github.com/pyviz/panel/archive/v{{ version }}.tar.gz
  sha256: 7eb64e7f4c92858219283a84cb5a008cc31e95e879e9bb40ae472ef6c9a83edc

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt"

requirements:
  host:
    - python
    - pip
    - param >=1.8.1
    - pyct >=0.4.4
    - setuptools >=30.3.0
    - nodejs ==9.11.1
  run:
    - bokeh >=1.0.0
    - param >=1.8.1
    - pyviz_comms >=0.6.0
    - markdown
    - testpath <0.4

test:
  imports:
    - panel

about:
  home: https://panel.pyviz.org
  summary: A high-level Python toolkit for composing widgets and plots
  description: |
    Panel provides tools for easily composing widgets, plots, tables, and other
    viewable objects and controls into control panels, apps, and dashboards.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - philippjfr
    - ocefpaf
