{% set name = "panel" %}
{% set version = "1.8.7" %}
{% set tests_to_skip = "test_reload_on_update" %}
{% set tests_to_skip = tests_to_skip + " or test_remote_file_provider_is_dir" %}
{% set tests_to_skip = tests_to_skip + " or test_remote_file_provider_ls" %}
{% set tests_to_skip = tests_to_skip + " or test_param_async_generator_abort or test_pass_bind_multi_async_generator_by_reference_and_abort" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_autoreload_app_local_module" %}  # [linux]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 76c9822e899ee08b945e562c3ae8e028e508019fd61ba0129abbf24d02ea031d

build:
  number: 0
  skip: true  # [py<310]
  entry_points:
    - panel = panel.command:main
  script:
    - {{ PYTHON }} -m pip install . -vv  --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - hatchling
    - hatch-vcs
    - param >=2.1.0
    - bokeh >=3.7.0,<3.9.0
    - pyviz_comms >=0.7.4
    - requests
    - packaging
    - nodejs >=18
  run:
    - python
    - bokeh >=3.7.0,<3.9.0
    - param >=2.1.0,<3.0
    - pyviz_comms >=2.0.0
    - markdown
    - markdown-it-py
    - linkify-it-py
    - mdit-py-plugins
    - narwhals >=2
    - requests
    - bleach
    - typing-extensions
    - pandas >=1.2
    - packaging
    - tqdm
    - pyviz-comms >=2.0.0
    - typing_extensions
  run_constrained:
    - holoviews >=1.18.0
    # set bokeh-fastapi bounds as discussed in https://github.com/AnacondaRecipes/panel-feedstock/pull/39
    - bokeh-fastapi >=0.1.5,<0.2.0

# E TypeError: 'async_generator' object is not callable
# E AttributeError: 'async_generator' object has no attribute 'isdir'
# E AttributeError: 'async_generator' object has no attribute 'ls'
# >       assert text_input.width == 121
# E       assert 111 == 121
# E        +  where 111 = TextInput(width=111).width
#             r2 = requests.get(f"http://localhost:{port}/{app_name}")
#             assert r2.status_code == 200
# >           assert "<title>B</title>" in r2.content.decode('utf-8')
test:
  imports:
    - panel
    - panel.io
  requires:
    - pip
    - pytest
    - pytest-tornasync
    - esbuild
    - nodejs
  commands:
    - pip check
    - panel --help
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest --pyargs -k "not({{ tests_to_skip }})" panel.tests

about:
  home: https://panel.holoviz.org
  summary: The powerful data exploration & web app framework for Python
  description: |
    Panel provides tools for easily composing widgets, plots, tables, and other
    viewable objects and controls into control panels, apps, and dashboards.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://panel.holoviz.org
  dev_url: https://github.com/holoviz/panel

extra:
  recipe-maintainers:
    - philippjfr
  skip-lints:
    - python_build_tool_in_run
    - host_section_needs_exact_pinnings
