{% set version = "0.7.0" %}

package:
  name: panel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/panel/panel-{{ version }}.tar.gz
  sha256: 71d446f469b424cb190bc896e78d0415b2bbebf17c6e5b024ed1a73b4448f8f4

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - pyct >=0.4.4
    - nodejs >=9.11.1
  run:
    - bokeh >=1.4.0
    - param >=1.9.2
    - pyviz_comms >=0.7.2
    - markdown
    - pyct >=0.4.4
test:
  imports:
    - panel

about:
  home: https://panel.pyviz.org
  summary: A high-level Python toolkit for composing widgets and plots
  description: |
    Panel provides tools for easily composing widgets, plots, tables, and other
    viewable objects and controls into control panels, apps, and dashboards.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - philippjfr
    - ocefpaf
