{% set version = "0.6.3" %}

package:
  name: panel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/panel/panel-{{ version }}.tar.gz
  sha256: 8ef8ff428730cdee787d36ec55ba3e18f7c10373946682d3c09eb9737b235337

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - pyct >=0.4.4
  run:
    - bokeh >=1.3.0
    - param >=1.9.1
    - pyviz_comms >=0.7.2
    - markdown
    - pyct >=0.4.4

test:
  imports:
    - panel

about:
  home: https://panel.pyviz.org
  summary: A high-level Python toolkit for composing widgets and plots
  description: |
    Panel provides tools for easily composing widgets, plots, tables, and other
    viewable objects and controls into control panels, apps, and dashboards.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - philippjfr
    - ocefpaf
