{% set version = "0.12.2" %}

package:
  name: panel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/panel/panel-{{ version }}.tar.gz
  sha256: edc81991ed3ca1c81949f853284de6826f13e5e9e78f444d2e5e5e440256588f

build:
  number: 0
  noarch: python
  entry_points:
    - panel = panel.command:main
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    # These are also needed at build time.
    - pyct >=0.4.4
    - param >=1.10.0
    - bokeh >=2.3,<2.4
    - nodejs >=10.13.0
    - pyviz_comms >=0.7.4
    - requests
    - packaging
    - tqdm
    - bleach
    - setuptools >=30.3.0
    - wheel
  run:
    - python >=3
    - bokeh >=2.3,<2.4
    - markdown
    - param >=1.10.0
    - pyct >=0.4.4
    - pyviz_comms >=0.7.4
    - tqdm
    - requests
    - bleach

test:
  imports:
    - panel
    - panel.io
  requires:
    - pip
    - colorama
  commands:
    - pip check
    - panel --help

about:
  home: https://panel.holoviz.org
  summary: A high-level app and dashboarding solution for Python
  description: |
    Panel provides tools for easily composing widgets, plots, tables, and other
    viewable objects and controls into control panels, apps, and dashboards.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://panel.holoviz.org/
  dev_url: https://github.com/holoviz/panel

extra:
  recipe-maintainers:
    - philippjfr
    - ocefpaf