{% set version = "1.2.3" %}

package:
  name: panel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/panel/panel-{{ version }}.tar.gz
  sha256: 5a9160fe084f918cb0900b6a4ef62d3ce542fcd2b8907d0b94113f13a8eea2d3

build:
  number: 0
  # nodejs currently isn't available on s390x
  skip: True  # [py<38 or s390x]
  entry_points:
    - panel = panel.command:main
  script:
    - {{ PYTHON }} -m pip install . -vv  --no-deps --no-build-isolation

requirements:
  host:
    - packaging
    - python
    - pip
    - setuptools
    - wheel
    # These are also needed at build time.
    - bleach 4.1.0
    - bokeh 3.1.1 # [py<39]
    - bokeh 3.2.0 # [py>=39]
    - pyct 0.5.0
    - param 1.13.0
    - pyviz_comms 2.3.0
    - nodejs 16.13.1
    - requests 2.31.0
    - tqdm 4.65.0
  run:
    - python
    - bokeh >=3.1.1,<3.3
    - param >=1.12.0
    - pyviz_comms >=0.7.4
    - markdown
    - markdown-it-py
    - linkify-it-py
    - mdit-py-plugins
    - requests
    - tqdm >=4.48.0
    - bleach
    - typing_extensions
    - pandas >=1.2
  run_constrained:
    - holoviews >=1.16.0

test:
  imports:
    - panel
    - panel.io
  requires:
    - pip
  commands:
    - pip check
    - panel --help

about:
  home: https://panel.holoviz.org
  summary: The powerful data exploration & web app framework for Python
  description: |
    Panel provides tools for easily composing widgets, plots, tables, and other
    viewable objects and controls into control panels, apps, and dashboards.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://panel.holoviz.org/
  dev_url: https://github.com/holoviz/panel

extra:
  recipe-maintainers:
    - philippjfr
  skip-lints:
    - python_build_tool_in_run
