{% set version = "0.9.6" %}

package:
  name: panel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/panel/panel-{{ version }}.tar.gz
  sha256: 8a64c988f54c16ca3c9b4b94ec08ba5e26694eebff83d56d14b8e554c37b1243
  patches:
    - index-ts-fix.patch

build:
  number: 0
  noarch: python
  entry_points:
    - panel = panel.cli:main
  script:
    # first two lines can probably be dropped in the next release.
    - rm -r panel/dist
    - cp {{ RECIPE_DIR }}/index.ts {{ SRC_DIR }}/panel/
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    # These are also needed at build time.
    - pyct
    - bokeh >=2.0
    - nodejs >=10.13.0
  run:
    - python >=3
    - bokeh >=2.0
    - markdown
    - param >=1.9.3
    - pyct >=0.4.4
    - pyviz_comms >=0.7.4
    - tqdm

test:
  imports:
    - panel
    - panel.io
  commands:
    - pip check
    - panel --help
  requires:
    - pip

about:
  home: https://panel.holoviz.org
  summary: A high-level app and dashboarding solution for Python
  description: |
    Panel provides tools for easily composing widgets, plots, tables, and other
    viewable objects and controls into control panels, apps, and dashboards.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - philippjfr
    - ocefpaf
