{% set version = "0.9.1" %}

package:
  name: panel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/panel/panel-{{ version }}.tar.gz
  sha256: bdced1cbe5b7b2b9d15797ae03ee0ce011dd361dffd494405e5e521690eff73c

build:
  number: 0
  noarch: python
  entry_points: panel = panel.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - bokeh >=2.0
    - markdown
    - param >=1.9.2
    - pyct >=0.4.4
    - pyviz_comms >=0.7.4
    - tqdm

test:
  imports:
    - panel
    - panel.io
  commands:
    - pip check
    - panel --help
  requires:
    - pip

about:
  home: https://panel.holoviz.org
  summary: A high-level Python toolkit for composing widgets and plots
  description: |
    Panel provides tools for easily composing widgets, plots, tables, and other
    viewable objects and controls into control panels, apps, and dashboards.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - philippjfr
    - ocefpaf
