{% set name = "panel" %}
{% set version = "1.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/panel-{{ version }}.tar.gz
  sha256: a9b0d8faf0b4391454cc8370d2acc21c26f780376100aece30e778f53cd06f76

build:
  number: 0
  # nodejs currently isn't available on s390x
  skip: true  # [py<310 or s390x]
  entry_points:
    - panel = panel.command:main
  script:
    - {{ PYTHON }} -m pip install . -vv  --no-deps --no-build-isolation

requirements:
  host:
    - python
    - hatchling
    - hatch-vcs
    - param >=2.1.0
    - pyviz_comms >=0.7.4
    - nodejs 20.17
    - requests
    - packaging
    - pip
    - bokeh >=3.7.0,<3.8.0
  run:
    - python
    - bokeh >=3.5.0,<3.8.0
    - param >=2.1.0,<3.0
    - pyviz_comms >=2.0.0
    - markdown
    - markdown-it-py
    - linkify-it-py
    - mdit-py-plugins
    - requests
    - bleach
    - typing-extensions
    - pandas >=1.2
    - packaging
    - tqdm
    - typing_extensions
  run_constrained:
    - holoviews >=1.18.0
    # set bokeh-fastapi bounds as discussed in https://github.com/AnacondaRecipes/panel-feedstock/pull/39
    - bokeh-fastapi >=0.1.2,<0.2.0

test:
  imports:
    - panel
    - panel.io
  requires:
    - pip
  commands:
    - pip check
    - panel --help

about:
  home: https://panel.holoviz.org
  summary: The powerful data exploration & web app framework for Python
  description: |
    Panel provides tools for easily composing widgets, plots, tables, and other
    viewable objects and controls into control panels, apps, and dashboards.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://panel.holoviz.org/
  dev_url: https://github.com/holoviz/panel

extra:
  recipe-maintainers:
    - philippjfr
  skip-lints:
    - python_build_tool_in_run
    - host_section_needs_exact_pinnings
