{% set version = "1.2.1" %}

package:
  name: panel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/panel/panel-{{ version }}.tar.gz
  sha256: abf2e601c609c610fdbac4929a046afae5874e06ea397c9f28262f56668f1b24

build:
  number: 0
  # nodejs currently isn't available on s390x
  skip: True  # [py<38 or s390x]
  entry_points:
    - panel = panel.command:main
  script:
    - {{ PYTHON }} -m pip install . -vv  --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    # These are also needed at build time.
    - bleach
    - bokeh 3.2.0
    - nodejs
    - pyct
    - packaging
    - param
    - pyviz_comms
    - requests
    - tqdm
  run:
    - python
    - bleach
    - packaging
    - bokeh >=3.1.1,<3.3
    - markdown
    - param >=1.12.0
    - pyviz_comms >=0.7.4
    - requests
    - tqdm >=4.48.0
    - typing_extensions
    - markdown-it-py
    - linkify-it-py
    - mdit-py-plugins
  run_constrained:
    - holoviews >=1.16.0

test:
  imports:
    - panel
    - panel.io
  requires:
    - pip
  commands:
    - pip check
    - panel --help

about:
  home: https://panel.holoviz.org
  summary: The powerful data exploration & web app framework for Python
  description: |
    Panel provides tools for easily composing widgets, plots, tables, and other
    viewable objects and controls into control panels, apps, and dashboards.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://panel.holoviz.org/
  dev_url: https://github.com/holoviz/panel

extra:
  recipe-maintainers:
    - philippjfr
  skip-lints:
    - python_build_tool_in_run
    - host_section_needs_exact_pinnings
